options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/edgar-explorer', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/edgar-explorer']

  # # Step 3: Get secret from Secret Manager and set corresponding ENV VAR
  # - name: 'google/cloud-sdk'  # Uses the Cloud SDK to access Secret Manager
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       echo "Fetching secret from Secret Manager..."
  #       gcloud secrets versions access latest --secret=edgar-ui-user-key > /workspace/secret.json

  # # Step 4: Set ENV VAR using keys in secret
  # - name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       export ADMIN_USERNAME=$(jq -r '.admin_username' /workspace/secret.json)
  #       export ADMIN_PASSWORD=$(jq -r '.admin_password' /workspace/secret.json)
  #       export DATASETID=$(jq -r '.dataset_id' /workspace/secret.json)
  #       export SECRET_KEY=$(jq -r '.secret_key' /workspace/secret.json)
  #       export DEBUG=$(jq -r '.debug' /workspace/secret.json)

  # Step 5: Deploy to Cloud Run with secrets and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'edgar-explorer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/edgar-explorer'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - 'GOOGLE_APPLICATION_CREDENTIALS_JSON=projects/$PROJECT_ID/secrets/edgar-ui-user-key/versions/latest'
      # - '--set-env-vars'
      # - 'ADMIN_USERNAME=$ADMIN_USERNAME,ADMIN_PASSWORD=$ADMIN_PASSWORD,DATASET_ID=$DATASET_ID,SECRET_KEY=$DATASET_ID,DEBUG=$DEBUG'

images:
  - 'gcr.io/$PROJECT_ID/edgar-explorer'
