steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/edgar-explorer', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/edgar-explorer']

  # Step 3: Deploy to Cloud Run with secrets and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'edgar-explorer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/edgar-explorer'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - 'GOOGLE_APPLICATION_CREDENTIALS_JSON=projects/$PROJECT_ID/secrets/edgar-ui-user-key/versions/latest'
      - '--update-secrets'
      - 'JSON_SECRET=projects/$PROJECT_ID/secrets/edgar-ui-config/versions/latest'
      - '--set-env-vars'
      - 'ADMIN_USERNAME=$(printf $${JSON_SECRET} | jq -r ".admin_username"),ADMIN_PASSWORD=$(printf $${JSON_SECRET} | jq -r ".admin_password"),DATASET_ID=$(printf $${JSON_SECRET} | jq -r ".dataset_id"),SECRET_KEY=$(printf $${JSON_SECRET} | jq -r ".secret_key").DEBUG=0'

images:
  - 'gcr.io/$PROJECT_ID/edgar-explorer'
