substitutions:
  _REGION: "us-central1"
  _RUNTIME: "python312"
  _IMAGE_NAME: "edgar-explore_r"
  _DATASET_ID: "edgar2"
  _DEBUG: "0"
  _SERVICE_ACCOUNT_CREDENTIAL_SECRET: "edgar-ui-user-key"
  _APP_CONFIG_SECRET: "edgar-ui-config"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}", "."]

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}"]

  # Step 3: Deploy to Cloud Run with secrets and environment variables
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_IMAGE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/${_IMAGE_NAME}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8000"
      - "--update-secrets=GOOGLE_APPLICATION_CREDENTIALS_JSON=${_SERVICE_ACCOUNT_CREDENTIAL_SECRET}:latest"
      - "--update-secrets=/secrets/app_config.env=${_APP_CONFIG_SECRET}:latest"
      - "--set-env-vars=DATASET_ID=${_DATASET_ID},DEBUG=${_DEBUG}"

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}"
