# Generated by Django 5.1.4 on 2025-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cik", models.CharField(max_length=10, verbose_name="CIK")),
                (
                    "company_name",
                    models.CharField(max_length=150, verbose_name="Company Name"),
                ),
                ("form_type", models.CharField(max_length=20, verbose_name="Form Type")),
                (
                    "date_filed",
                    models.CharField(max_length=10, verbose_name="Date Filed"),
                ),
                (
                    "filename",
                    models.CharField(max_length=100, verbose_name="EDGAR file name"),
                ),
                (
                    "accession_number",
                    models.CharField(max_length=20, verbose_name="Accession Number"),
                ),
                (
                    "chunks_used",
                    models.CharField(max_length=100, null=True, verbose_name="Chunks"),
                ),
                ("num_trustees", models.IntegerField(null=True, verbose_name="Trustees")),
                (
                    "trustees_comp",
                    models.CharField(
                        max_length=4096, null=True, verbose_name="Trustees Compensation"
                    ),
                ),
            ],
            options={
                "verbose_name": "SEC Filing in Master Index",
                "verbose_name_plural": "SEC Filings in Master Index",
            },
        ),
    ]
