# Generated by Django 5.1.4 on 2025-01-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilingIndexEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cik", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=150)),
                ("form_type", models.CharField(max_length=20)),
                ("date_filed", models.CharField(max_length=10)),
                ("filename", models.CharField(max_length=100)),
                ("accession_number", models.CharField(max_length=20)),
            ],
        ),
    ]
