# Generated by Django 5.1.4 on 2025-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cik", models.CharField(max_length=10, verbose_name="CIK")),
                (
                    "company_name",
                    models.CharField(max_length=150, verbose_name="Company Name"),
                ),
                ("form_type", models.CharField(max_length=20, verbose_name="Form Type")),
                (
                    "date_filed",
                    models.CharField(max_length=10, verbose_name="Date Filed"),
                ),
                (
                    "accession_number",
                    models.CharField(max_length=20, verbose_name="Accession Number"),
                ),
                (
                    "responses",
                    models.JSONField(default=list, null=True, verbose_name="Responses"),
                ),
                (
                    "batch_id",
                    models.CharField(max_length=20, null=True, verbose_name="Batch ID"),
                ),
                (
                    "info_type",
                    models.CharField(
                        max_length=16, null=True, verbose_name="Information Type"
                    ),
                ),
            ],
            options={
                "verbose_name": "SEC Filing in Master Index",
                "verbose_name_plural": "SEC Filings in Master Index",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cik", "accession_number", "batch_id"),
                        name="unique_filing_constraint",
                    )
                ],
            },
        ),
    ]
