# Generated by Django 5.1.4 on 2025-01-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="relevant_text",
            field=models.CharField(max_length=8192, null=True, verbose_name="Chunks"),
        ),
    ]
