# Generated by Django 5.1.4 on 2025-04-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="filing",
            constraint=models.UniqueConstraint(
                fields=("cik", "accession_number", "batch_id"),
                name="unique_filing_constraint",
            ),
        ),
    ]
