# Generated by Django 5.1.4 on 2025-08-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="chunks",
            field=models.JSONField(default=list, null=True, verbose_name="Chunk Numbers"),
        ),
        migrations.AddField(
            model_name="filing",
            name="texts",
            field=models.JSONField(default=list, null=True, verbose_name="Chunk Texts"),
        ),
    ]
