# Generated by Django 5.1.4 on 2025-03-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0002_filing_relevant_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="batch_id",
            field=models.CharField(max_length=20, null=True, verbose_name="Batch ID"),
        ),
    ]
