# Generated by Django 5.1.4 on 2025-08-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0002_filing_chunks_filing_texts"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="num_citations",
            field=models.IntegerField(default=0, verbose_name="Number of Citations"),
        ),
    ]
