# Generated by Django 5.1.4 on 2025-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0003_filing_num_citations"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="num_responses",
            field=models.IntegerField(default=0, verbose_name="Number of Responses"),
        ),
    ]
