# Generated by Django 5.1.4 on 2025-08-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0004_filing_num_responses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filing",
            name="num_citations",
        ),
        migrations.AddField(
            model_name="filing",
            name="citation_positions",
            field=models.JSONField(
                default=list, null=True, verbose_name="Citation Positions"
            ),
        ),
    ]
