# Generated by Django 5.1.4 on 2025-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0005_remove_filing_num_citations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="model",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Model"
            ),
        ),
    ]
