# Generated by Django 5.1.4 on 2025-08-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edgar_explorer", "0006_filing_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="filing",
            name="cost",
            field=models.FloatField(default=0.0, verbose_name="Cost"),
        ),
    ]
